[package]
name = "batch_rename"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.4", features = ["smol"]}
iced_native = "0.4"
rfd = "0.10.0"
